---
# vim: set ts=2 et sw=2 ft=yaml tw=0
workflow:
  rules:
  # Never run merge request pipelines
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    when: never
  # Only run on git.aspn.us
  - if: $CI_SERVER_HOST == "git.aspn.us"

variables:
  GIT_CLEAN_FLAGS: -xdffe packagecache

default:
    before_script:
        # Clone only if empty directory
        - |
            if ! [ "$(ls -A)" ]; then
                git clone $CI_REPOSITORY_URL .
            fi
        - git remote set-url origin $CI_REPOSITORY_URL
        - git --no-optional-locks fetch --prune
        - git reset --hard "$CI_COMMIT_SHA"
        - git clean "$GIT_CLEAN_FLAGS" || true

        # If this is a branch pipeline, attempt to merge with master/target branch, but keep going
        # if it fails.
        - |
            if [[ ! -z "${CI_COMMIT_BRANCH}" ]]; then
                git merge origin/"${TARGET_BRANCH:-$CI_DEFAULT_BRANCH}" || true
                git reset --hard
                git clean "$GIT_CLEAN_FLAGS"
            fi

stages:
- packaging

build and deploy wheel:
  stage: packaging
  tags:
    - linux-light-runner
  script:
    # Build docker image.
    - docker pull ubuntu:24.04
    # Use special tag name, --build-arg, and --cache-from args to utilize cache on CI.
    - export DOCKER_IMAGE="$LOCAL_REGISTRY_CACHE/pntos-python"
    - docker build --cache-from $DOCKER_IMAGE --build-arg BUILDKIT_INLINE_CACHE=1 -t $DOCKER_IMAGE -f Dockerfile .
    # Push to cache.
    - docker push $DOCKER_IMAGE

    # Build the wheel.
    - docker run -it --rm -v $(pwd):/work $DOCKER_IMAGE "pip wheel -v ."
    # Sanity-check the wheel.
    - docker run -it --rm -v $(pwd):/work $DOCKER_IMAGE "pip install *.whl --break-system-packages"
    # Deploy the wheel
    - docker run -it --rm -v $(pwd):/work $DOCKER_IMAGE "twine upload
        --repository-url ${CI_API_V4_URL}/projects/94/packages/pypi
        --username gitlab-ci-token
        --password ${CI_JOB_TOKEN}
        --skip-existing
        *.whl"
