[project]
name = "pntos-python-docs-data"
version = "0.4.0"
description = "Assets to build pntOS-Python documentation."
authors = [{ name = "IS4S", email = "pntos@is4s.com" }]
dependencies = []
readme = "README.md"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = ["branding/**"]

[tool.hatch.build.targets.wheel]
include = ["branding/**"]
